Repository openshift/origin-metrics, pull requests merged in 2018-02, with the labels that each got.

#404 [BZ 1508496] do case insensitive comparison
  cassandra/cassandra-docker.sh
  hawkular-metrics/standalone.conf
Labels: size/XS

#400 Upgrade to Cassandra 3.0.15
  cassandra/Dockerfile
  cassandra/apache-cassandra-3.0.15-bin.tar.gz.md5
Labels: size/M

#401 Add support for building dev images
  .gitignore
  hack/build-images.sh
  hawkular-metrics/Dockerfile
  hawkular-metrics/dev/README.adoc
Labels: size/S

#402 Remove alerts
  hawkular-metrics/Dockerfile
  hawkular-metrics/standalone.xml
Labels: size/M

#403 Suppress unlogged batch warnings in Cassandra logs
  cassandra/cassandra.yaml.template
Labels: size/XS
